name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      CI: true
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Enable Corepack + activate Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn cedar lint

      - name: Type-check
        run: yarn cedar type-check

      - name: Test (non-watch)
        run: yarn cedar test --watch=false
