name: Deploy

on:
  push:
    tags:
      - '*.*.*'
      - 'v*.*.*'

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      CI: true
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Enable Corepack + activate Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn cedar lint

      - name: Type-check
        run: yarn cedar type-check

      - name: Test (non-watch)
        run: yarn cedar test --watch=false

  deploy:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Trigger Coolify (demo)
        if: ${{ secrets.COOLIFY_WEBHOOK_DEMO != '' }}
        env:
          COOLIFY_WEBHOOK_DEMO: ${{ secrets.COOLIFY_WEBHOOK_DEMO }}
          COOLIFY_TOKEN_DEMO: ${{ secrets.COOLIFY_TOKEN_DEMO }}
        run: |
          if [ -n "$COOLIFY_TOKEN_DEMO" ]; then
            curl -fsSL -X POST -H "Authorization: Bearer $COOLIFY_TOKEN_DEMO" "$COOLIFY_WEBHOOK_DEMO"
          else
            curl -fsSL -X POST "$COOLIFY_WEBHOOK_DEMO"
          fi

      - name: Trigger Coolify (private)
        if: ${{ secrets.COOLIFY_WEBHOOK_PRIVATE != '' }}
        env:
          COOLIFY_WEBHOOK_PRIVATE: ${{ secrets.COOLIFY_WEBHOOK_PRIVATE }}
          COOLIFY_TOKEN_PRIVATE: ${{ secrets.COOLIFY_TOKEN_PRIVATE }}
        run: |
          if [ -n "$COOLIFY_TOKEN_PRIVATE" ]; then
            curl -fsSL -X POST -H "Authorization: Bearer $COOLIFY_TOKEN_PRIVATE" "$COOLIFY_WEBHOOK_PRIVATE"
          else
            curl -fsSL -X POST "$COOLIFY_WEBHOOK_PRIVATE"
          fi
