name: Deploy

on:
  push:
    tags:
      - '*.*.*'
      - 'v*.*.*'

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      CI: true
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack + activate Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn cedar lint

      - name: Type-check
        run: yarn cedar type-check

      - name: Test (non-watch)
        run: yarn cedar test --watch=false

  deploy:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Fail if no Coolify webhooks configured
        if: ${{ secrets.COOLIFY_WEBHOOK_DEMO == '' && secrets.COOLIFY_WEBHOOK_PRIVATE == '' }}
        run: |
          echo "Neither COOLIFY_WEBHOOK_DEMO nor COOLIFY_WEBHOOK_PRIVATE is set."
          echo "Refusing to report success without triggering a deployment."
          exit 1

      - name: Trigger Coolify webhooks
        if: ${{ secrets.COOLIFY_WEBHOOK_DEMO != '' || secrets.COOLIFY_WEBHOOK_PRIVATE != '' }}
        env:
          COOLIFY_WEBHOOK_DEMO: ${{ secrets.COOLIFY_WEBHOOK_DEMO }}
          COOLIFY_TOKEN_DEMO: ${{ secrets.COOLIFY_TOKEN_DEMO }}
          COOLIFY_WEBHOOK_PRIVATE: ${{ secrets.COOLIFY_WEBHOOK_PRIVATE }}
          COOLIFY_TOKEN_PERSONAL: ${{ secrets.COOLIFY_TOKEN_PERSONAL }}
        run: |
          set -u

          redact_url() {
            # Avoid leaking secret webhook paths/tokens in logs.
            # Print only the origin, e.g. https://coolify.example.com
            echo "$1" | sed -E 's#(https?://[^/]+).*#\1#'
          }

          trigger_webhook() {
            local name="$1"
            local url="$2"
            local token="$3"

            if [ -z "${url:-}" ]; then
              return 0
            fi

            echo "::group::Trigger Coolify (${name})"
            echo "url=$(redact_url "$url")"

            local headers_file
            local body_file
            headers_file="$(mktemp)"
            body_file="$(mktemp)"

            local curl_exit=0
            local http_code=""
            local time_total=""
            local curl_out=""

            if [ -n "${token:-}" ]; then
              curl_out="$(curl --http1.1 --retry 3 --retry-all-errors --retry-delay 2 \
                -sS -X GET \
                -H "Authorization: Bearer $token" \
                -D "$headers_file" \
                -o "$body_file" \
                -w '%{http_code} %{time_total} remote=%{remote_ip} local=%{local_ip} ssl=%{ssl_verify_result}' \
                "$url" || curl_exit=$?)"
            else
              curl_out="$(curl --http1.1 --retry 3 --retry-all-errors --retry-delay 2 \
                -sS -X GET \
                -D "$headers_file" \
                -o "$body_file" \
                -w '%{http_code} %{time_total} remote=%{remote_ip} local=%{local_ip} ssl=%{ssl_verify_result}' \
                "$url" || curl_exit=$?)"
            fi

            http_code="${curl_out%% *}"
            time_total="${curl_out#* }"
            if [ "$time_total" = "$curl_out" ]; then
              time_total=""
            fi

            echo "curl_exit=${curl_exit} http_code=${http_code} time_total=${time_total}s"
            echo "curl_meta=${curl_out#* }"
            echo "-- response headers (first 200 lines) --"
            sed -n '1,200p' "$headers_file" || true
            echo "-- response body (first 4096 bytes) --"
            head -c 4096 "$body_file" || true
            echo

            rm -f "$headers_file" "$body_file" || true
            echo "::endgroup::"

            if [ "$curl_exit" -ne 0 ]; then
              return 1
            fi

            case "$http_code" in
              2*|3*) return 0 ;;
              *) return 1 ;;
            esac
          }

          failed=0

          if ! trigger_webhook "demo" "${COOLIFY_WEBHOOK_DEMO:-}" "${COOLIFY_TOKEN_DEMO:-}"; then
            failed=1
          fi

          if ! trigger_webhook "private" "${COOLIFY_WEBHOOK_PRIVATE:-}" "${COOLIFY_TOKEN_PERSONAL:-}"; then
            failed=1
          fi

          if [ "$failed" -ne 0 ]; then
            echo "One or more Coolify webhook triggers failed."
            exit 1
          fi
